### ISSUE TITLE
Backticks issue 

### ISSUE THREAD

**Issue by antonstan** [follow-redirects/follow-redirects#104]
Issue is happening with old Node's version like 0.10.*. I deploy Node app to Apigee Edge Proxy and this one doesn't support ES6+. Could you, please replace with concat? 

https://github.com/follow-redirects/follow-redirects/blob/faf71bd1afae90c6c300dfb8dbf9d2b1516d24c1/index.js#L390

**Comment by RubenVerborgh** [comment]
I could, but that's not going to help. For multiple reasons, this package is only compatible with Node 4 and up (https://github.com/follow-redirects/follow-redirects/blob/v1.6.0/package.json#L7).

**Comment by RubenVerborgh** [comment]
This was apparently causing more issues: https://github.com/follow-redirects/follow-redirects/commit/37f4e7c5d0abb29021042d3a4ce3fd300d28180b#commitcomment-31827074 (although I'm not sure for how much longer we want to support obsolete tooling).
