### ISSUE TITLE
Returns error no tel:// links

### ISSUE THREAD

**Issue by tijevlam** [follow-redirects/follow-redirects#110]
I have this link: https://e.fletcher.nl/1/4/1771/1/-jGt6rTuMg4xtL1uhkkIpJpYBnfUEGlL8QiS5KhAFe-gQhvmrwt15ebGab_09AEey86Qyle7hVzRIhpyiCWPnw when i follow-redirect it, it crashes telling me tel:// is not a valid protocol. I get that it is, but i dont want my code to stop running. I want it to return the tel-link as an endpoint. Can we have the plugin recognize that. Or more generally speaking have an option to use user-defined endpoints?  (eg. tel-links, certain domains, urls etc)??

**Comment by RubenVerborgh** [comment]
If specific for `tel`, consider looking into https://github.com/follow-redirects/follow-redirects#advanced-usage

**Comment by tijevlam** [comment]
Thanks for the wuick reply. I’ve read the advanced part of the readme but it did not became completely clear to me. Are you suggesting something kinke this:

```
var followRedirects = require('follow-redirects').wrap({
  tel: my-custom-function(){
     return "this is a telephone link, not following any further";
}
});
```

**Comment by RubenVerborgh** [comment]
Probably more like
```javascript
{
  tel: {
    request: (options, callback) {
      callback(null, { phone: options.url , headers: {} });
    }
  }
}
```
where the callback object pretends to be an `HttpResponse`.

**Comment by tijevlam** [comment]
Hi @RubenVerborgh,

I wrote the following short versioned test-script checking this specific url. But I still get an unsupported protocol error. Could you help me out, where I'm going wrong?

```
'use strict';
var http = require('follow-redirects').http,
      https = require('follow-redirects').https,
      url = require('url'),
     followRedirects = require('follow-redirects').wrap({
        tel: {
            request: function(options, callback) {
                console.log(options);
                callback(null, { responseUrl:responseUrl, phone: options, headers: {} });
            },
            get: function(options, callback) {
                console.log(options);
                callback(null, { phone: options, headers: {} });
            }
        }
    });

var result = [];
const options = url.parse("https://e.fletcher.nl/1/4/1771/1/-jGt6rTuMg4xtL1uhkkIpJpYBnfUEGlL8QiS5KhAFe-gQhvmrwt15ebGab_09AEey86Qyle7hVzRIhpyiCWPnw");

options.trackRedirects = true;

https.get(options, function (response) {
    result[0] = {index: 0, start: response.redirects[0].url, destination: response.responseUrl, redirectCount: response.redirects.length-1, redirects: response.redirects};
    console.log(response.redirects);
}).on('error', function (err) {
  console.error(err);
});
```

**Comment by RubenVerborgh** [comment]
> Could you help me out, where I'm going wrong?

You're not actually using the wrapped version `followRedirects` that you create, so the `tel` code is simply not used.

You'll want something like:

```
const { http, https } = require('follow-redirects').wrap({
  http: require('http'),
  https: require('https'),
  tel: { /* … */ },
});

**Comment by tijevlam** [comment]
I feel like a noob, sorry. And thank you so much for your help. I'm still not completely where I wanted to be as i now get a different error:

```
request._redirectable = this;
                        ^

TypeError: Cannot set property '_redirectable' of undefined
```

With different settings I also got this error frequently:

```
var location = response.headers.location;
                                  ^
TypeError: Cannot read property 'location' of undefined
```

I've got the impression that i'm not sending the right parameters in the callback. Should i at least have some headers? Or should I, in a certain way, let the script now it is done redirecting?

Just to be sure, this is the code I'm running now:
```javascript
'use strict';
var url = require('url');

const { http, https } = require('follow-redirects').wrap({
  http: require('http'),
  https: require('https'),
  tel: {
        request: function(options, callback) {
            callback(options, { phone: options, headers: {} });
        }

//This is the code that gave the other error:
    /* request: function(options, callback) {
                //console.log(options.href);
                callback(options, {phone: options, headers: {statusCode: 200, statusMessage: "OK", location: options.href} });
            }
*/
// the null as first parameter of the callback gives me the error that the headers could'nt be found 

        }
    });

var link = "https://e.fletcher.nl/1/4/1771/1/-jGt6rTuMg4xtL1uhkkIpJpYBnfUEGlL8QiS5KhAFe-gQhvmrwt15ebGab_09AEey86Qyle7hVzRIhpyiCWPnw "

var result = [];
const options = url.parse(link);
options.trackRedirects = true;

https.get(options, function (response) {
    console.log(response);
}).on('error', function (err) {
  console.error(err);
});
```
Could you spare a little more time to help me out?

**Comment by RubenVerborgh** [comment]
There you go:

```javascript
const url = require('url');
const EventEmitter = require('events');

const { http, https } = require('.').wrap({
  http: require('http'),
  https: require('https'),
  tel: {
    request: (options, callback) => {
      callback(options, { phone: options, headers: {} });
      return new class extends EventEmitter { end() {} };
    }
  },
})


const result = [];
const options = url.parse("https://e.fletcher.nl/1/4/1771/1/-jGt6rTuMg4xtL1uhkkIpJpYBnfUEGlL8QiS5KhAFe-gQhvmrwt15ebGab_09AEey86Qyle7hVzRIhpyiCWPnw");

https.get(options, response => console.log(response.href))
     .on('error', console.error);
```

**Comment by tijevlam** [comment]
Thank you so much... this works. But not completely. The request returns nicely but it doesn't fill the `responseUrl` or `redirects` object which kinda defeats the purpose of using this plugin :-s.

I've tried a couple of things. If I add a statusCode to the callback it does get pushed to the `redirects` object, but the responseUrl doesn't. 

Do you have any suggestions?

**Comment by RubenVerborgh** [comment]
There was a timing issue in the above code; updated by adding `setImmediate`.

**Comment by tijevlam** [comment]
Wow! That fixed it... thanks for being a great help.
