### ISSUE TITLE
Question: how to configure "options"-object for redirect requests?

### ISSUE THREAD

**Issue by claasahl** [follow-redirects/follow-redirects#114]
### Situation

1. I am making a GET request with an "Authorization"-header (works fine)
1. The server replies with a redirect URL and a bunch of query parameters, some of which correspond to authentication credentials (also works fine)
1. I get redirected to the redirect URL, but this time the request includes both my original "Authorization"-header as well as the query parameters... In my case, this "confuses" the system that I am talking to.

### Questions

Is is possible to send one set of headers for the initial HTTP request and another set of headers when it comes to a redirect? In other words, is there a way to control the behavior that this PR #5 (issue #4) added? Can I turn this behavior on/off?

Hope this is somewhat clear.

Many thanks in advance.

**Comment by RubenVerborgh** [comment]
Good idea, following up in #115.
