### ISSUE TITLE
Newer versions of the debug dependency no longer work on Node 4

### ISSUE THREAD

**Issue by miron4dev** [follow-redirects/follow-redirects#116]
Update to Debug 4.11 is a breaking change. They started using `const` / `let` keywords from 4.x
See more https://github.com/visionmedia/debug/issues/604

Please revert this update or release major version instead.

**Comment by RubenVerborgh** [comment]
`follow-redirects` only offers [compatibility with Node 6.x](https://github.com/follow-redirects/follow-redirects/blob/b7a8216d3014dd82a605bd36e8756cd40936878c/package.json#L10) and is tested for compatibility with Node 6.x on every commit. So the build is not broken.

> Please revert this update

An update was needed for security reasons.

> or release major version instead

Major version releases are for breaking API changes; there are none in this release.

**Comment by RubenVerborgh** [comment]
I will reconsider this one, since it has been reported a second time. Also, I correct my earlier remark: the `debug` dependency was not the one with a security problem.

**Comment by RubenVerborgh** [comment]
v1.8.1 supports Node 4 again. Thanks for nudging me.
