### ISSUE TITLE
Latest version 1.8.0 breaks backward compatability

### ISSUE THREAD

**Issue by cjperusse** [follow-redirects/follow-redirects#117]
Looks like the latest version, 1.8.0, has broken backward compatibility. The updated dependency on "debug" to 4.1.1 has broken our local builds, due to the usage of a "let" without "use strict" - Is there a chance you could revert this dependency back to previous version (3.2.6)?

**Comment by RubenVerborgh** [comment]
> has broken backward compatibility.

Not really. No backward incompatible changes have been made to the interface.

> The updated dependency on "debug" to 4.1.1 has broken our local builds

But indeed, the dependency was updated. This was also noted in #116. I'll see what I can do.
