### ISSUE TITLE
what you recommend..

### ISSUE THREAD

**Issue by determin1st** [follow-redirects/follow-redirects#127]
To use, with `follow-redirects` counter-part in the browser?

**Comment by RubenVerborgh** [comment]
Just the browser really. All that functionality is provided for you already, this library brings it to Node.

**Comment by determin1st** [comment]
I'm using Fetch API but the implementation of `redirect: follow` doesn't work well..
For example if I reach maximum redirect count, it doesn't return correct error from the API:
![EQ9vjEqWAAE-nhv](https://user-images.githubusercontent.com/16524081/75570591-3e3dc680-5a79-11ea-9bf8-4c828d32d54e.jpg)

It dumps it into console, as you can see..

**Comment by RubenVerborgh** [comment]
You should not run follow-redirects in the browser under any circumstance. It will not work; it’s designed for Node.js only. The browser has its own redirection mechanism that scripts cannot influence.

**Comment by determin1st** [comment]
> redirect
> The redirect mode to use: follow (automatically follow redirects), error (abort with an error if a redirect occurs), or manual (handle redirects manually). In Chrome the default is follow (before Chrome 47 it defaulted to manual).

It's from [fetch() definition](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch)

You may use same algorithms to do `redirect:manual` i guess..

**Comment by RubenVerborgh** [comment]
> You may use same algorithms to do `redirect:manual` i guess..

Mmm yes, but probably with some limitations. In any case, there's no need for the library in the browser; quite the contrary, it's bringing browser functionality to Node.

Here you can read advice for how to exclude the library for browser builds: https://github.com/follow-redirects/follow-redirects/tree/670c3a7b38e0707a22d111fa766b4e82d277ec41#browser-usage
