### ISSUE TITLE
do not switch from post to get on 308 status code

### ISSUE THREAD

**Issue by aseprano** [follow-redirects/follow-redirects#129]
I noticed that a server returning a 308 status code will cause the library to change the call method from POST to GET, whereas the standard clearly says that this is not allowed.

[Link to the RFC section](https://tools.ietf.org/html/rfc7538#section-3)

**Comment by RubenVerborgh** [comment]
We only switch (in certain conditions) on 301, 302, 303.

https://github.com/follow-redirects/follow-redirects/blob/master/index.js#L321-L331

**Comment by torkelrogstad** [comment]
Through using Axios, I'm getting my POST requests redirected to a GET request. I do not desire this. Would it make sense to expose a configuration of some sort to change this behavior?
