### ISSUE TITLE
Redirect from HTTP to HTTPS fails

### ISSUE THREAD

**Issue by justinormont** [follow-redirects/follow-redirects#130]
When an HTTP connection gets upgraded to HTTPS, the connection to the new redirected address fails.

Error:
`Redirected request failed: Protocol "https:" not supported. Expected "http:"`

Example URL:
http://mealplannerpro.com/images/recipes/recipes/0/271/271764/720826.jpg

**Comment by justinormont** [comment]
This seems related to setting the HTTP/HTTPS agent:
```
const httpAgent = new http.Agent({ maxSockets: 5 });  
const httpsAgent = new https.Agent({ maxSockets: 5 }); 
const httpOptions = { agent: httpAgent };
const httpsOptions = { agent: httpsAgent };
```

**Comment by RubenVerborgh** [comment]
Hi @justinormont, works for me with:

```
const { http } = require('follow-redirects');

http.get('http://mealplannerpro.com/images/recipes/recipes/0/271/271764/720826.jpg',
  r => console.log(r.headers));
```

Please add code to reproduce, as well as versions used.

**Comment by RubenVerborgh** [comment]
> agents (default: undefined) – sets the agent option per protocol, since HTTP and HTTPS use different agents. Example value: { http: new http.Agent(), https: new https.Agent() }

—https://github.com/follow-redirects/follow-redirects/blob/2ede36d7c60d3acdcd324dcd99a9dbd52e4fb3a6/README.md#per-request-options
