### ISSUE TITLE
Fatal error if error

### ISSUE THREAD

**Issue by BobFrankston** [follow-redirects/follow-redirects#131]
If there is any error in (such as a DNS failure)
```
 this._redirectable.emit(event, arg1, arg2, arg3);
```
(Index.js line 13)

If I pass a bad URL (like **https://null** in this case) I should get an error but the application should not abort. I tried simply catching the error but that didn't work so not sure what the fix it.

**Comment by RubenVerborgh** [comment]
The goal of follow-redirects is to behave like the original `http` library would, and it also errors.
You will want to attach an `error` listener.

```
const http = require('http');
const request = http.get('http://null');
request.on('error', console.log);
```

**Comment by BobFrankston** [comment]
Thank you.
