### ISSUE TITLE
Error while parsing chunked transfer body

### ISSUE THREAD

**Issue by supergithuber** [follow-redirects/follow-redirects#132]
res.on("data", function (chunk) {
            chunks.push(chunk);
            console.log(chunk.toString())
});

I got this:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 400 Bad Request</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 400 Bad Request</h1>
            <p>Sorry, the requested URL <tt>&#039;this is my request url&#039;</tt>
               caused an error:</p>
            <pre>Error while parsing chunked transfer body.</pre>
        </body>
    </html>

**Comment by RubenVerborgh** [comment]
I will need to the full code to reproduce this.
Right now, there's no indication that follow-redirects would be at fault.

**Comment by supergithuber** [comment]
I confirm that the error was emitted by server
