### ISSUE TITLE
it doesnot work

### ISSUE THREAD

**Issue by AkashWarlocks** [follow-redirects/follow-redirects#133]
`const request = require('request')
const { http, https } = require('follow-redirects');

    https.request({
        host: 'zoom.us',
        path: '/oauth/authorize?response_type=code&client_id=' + clientID + '&redirect_uri=' + redirectURL,
        maxRedirects:100
      }, (response) => {
        res.send(response.responseUrl)  
        // 'http://duckduckgo.com/robots.txt'
      });`

The sample shown also doesnor provide any output the code is stuck. is this library working ?

**Comment by RubenVerborgh** [comment]
This example doesn't work with the regular Node.js `https` API either; you need to call `.end()`. https://nodejs.org/api/http.html#http_request_end_data_encoding_callback
