### ISSUE TITLE
Can I be told that I was redirected?

### ISSUE THREAD

**Issue by elgs** [follow-redirects/follow-redirects#14]
It seems the `res.statusCode` always returns `200` even if I'm redirected. So is there any way I can be told I was redirected?

Thanks,
Elgs

**Comment by jamestalmage** [comment]
@elgs 
This is now resolved, but not yet pushed to npm. See the `README` where it discusses the `fetchedUrls` property

@olalonde ready for `npm publish`

**Comment by olalonde** [comment]
@jamestalmage published to 0.0.6. Do you have a npm account (`npm whoami`)? I'll give you access to the package so you can npm publish.

**Comment by jamestalmage** [comment]
This is me:
 https://www.npmjs.com/~james.talmage

Not near a pc right now.

**Comment by olalonde** [comment]
Ok thanks, added you.
