### ISSUE TITLE
Redirect / short URLs not working

### ISSUE THREAD

**Issue by alexpluto** [follow-redirects/follow-redirects#142]
Only certain short URLs that redirect are supported where meta data is returned.

e.g. https://abnb.me/fHw1T5PE68 - this is **not** working and no meaningful meta data is returned. When using this URL in: https://developers.facebook.com/tools/debug/ - you can see the meta data that should be returned after the redirect

e.g. https://bit.ly/322JENd - this is working as expected and returns meta data from the redirected URL.

**Comment by RubenVerborgh** [comment]
That's a bug in the web server, it returns 200 instead of 3xx:

```
$ curl -i -s https://abnb.me/fHw1T5PE68 | head
HTTP/1.1 200 OK
Server: openresty/1.13.6.2
Date: Tue, 25 Aug 2020 11:54:02 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 16340
Connection: keep-alive
X-Powered-By: Express
Set-Cookie: _s=XTa1x9aOEh0b1IAKR5J8l7josns8jPqqWdCkWmw7SUJW8C4qNZyDHoRGjjYPyQYR; Max-Age=31536000; Path=/; Expires=Wed, 25 Aug 2021 11:54:02 GMT
Last-Modified: Tue, 25 Aug 2020 11:54:02 GMT
ETag: W/"3fd4-KvSC15N31/EO0PCEfRqkB0CRBVk"
```

You can work around this yourself with the `beforeRedirect` option (see README).

**Comment by alexpluto** [comment]
Thanks you Ruben, we'll check this out.
