### ISSUE TITLE
Request never completes using promisify

### ISSUE THREAD

**Issue by wmelton** [follow-redirects/follow-redirects#154]
When wrapping `.request` in promisify, the function call hangs and never resolves.

Example:

```
const { http, https } = require("follow-redirects");
const resolved = util.promisify(https.request);

(async () => {
	const url = await resolved({ host: "google.com" });
	console.log("url", url);
})();
```

I've verified that when using the documented callback approach on the npm page these functions work as expected. However, when attempting to utilize async/await they hang.

**Comment by wmelton** [comment]
A quick update here. FWIW this works for people wanting to use async/await with this library. 

```
function resolveFunc(host, callback) {
	const request = https.request({ host }, (response) => {
		callback(null, response.responseUrl);
	});
	request.end();
}

const resolve = util.promisify(resolveFunc);
```

**Comment by omriLugasi** [comment]
Currently the api of `promisify` enforce you to add as your last argument of the function, a callback function that get 
```
(err, data) => {}
```
Adding such a thing will do breaking changes to the api.
Unfortunately this can't be solve also by adding `.promise()` to the `request` function, it will add breaking changes as well.

But in order to work with the `http` and `https` requests as a promise we can expose something simple like:
```
const response = await https.asyncRequest(input, options)
// OR
const response = await https.requestAsync(input, options)
```
@RubenVerborgh what you think, it worth a PR?

**Comment by RubenVerborgh** [comment]
Can't we just solve it the same way the Node API does?

**Comment by omriLugasi** [comment]
You are totally right ;/ 

From the Nodejs docs:
 _"Using the `util.promisify.custom` symbol one can override the return value of [util.promisify()](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original)."_

 _"This can be useful for cases where the original function does not follow the standard format of taking an error-first callback as the last argument."_

We can use `original[util.promisify.custom]` as mention [here](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_custom_promisified_functions) to help us promisified the `request` function and avoid from any breaking changes in the package API.


I would like to contribute this feature to the package, may I?

**Comment by RubenVerborgh** [comment]
> but we need to expose also the `RedirectableRequest` Object for modification

Why?

**Comment by omriLugasi** [comment]
**My concern is:**
`setHeader`, `removeHeader` , `abort`, `end` and more functions will be unreachable for the users.
According to the docs, we don't provide details about those functions, but they exposed through the `RedirectableRequest` Object.

Am I wrong? should I keep going with the PR and not expose the `RedirectableRequest`?

**Comment by RubenVerborgh** [comment]
We should do the same as Node:

```javascript
const http = require("http");
const resolved = util.promisify(https.request);

(async () => {
	const url = await resolved({ host: "perdu.com" });
	console.log("url", url);
})();
```

and this snippet hangs… so our behavior is correct here.

So sorry @wmelton @omriLugasi, but this works as intended. (`.get` can be promisified though)
