### ISSUE TITLE
can we keep the authorization header when it redirected from different host?

### ISSUE THREAD

**Issue by speed-of-light** [follow-redirects/follow-redirects#161]
I've checked this lib do check the host change and drop the `authorization` header accordingly.

https://github.com/follow-redirects/follow-redirects/blob/cdd921f16a76002e9be2f9124bbf89d7133ccb46/test/test.js#L1305

https://github.com/follow-redirects/follow-redirects/blob/cdd921f16a76002e9be2f9124bbf89d7133ccb46/index.js#L372

I could imagine for some cases that people wants to drop it for security concern, but in my scenario, with keeping the token in the header would do a lot help.

Compare to `curl` there is a `--location-trusted` option for redirections to keep headers. Could we added something similar to make this tool more flexible? Thanks.

Besides adding an option for this, could we make the option somehow globally or configured as on an instance so that could be passed to other caller?

**Comment by RubenVerborgh** [comment]
You can tap into the `beforeRedirect` hook to make this change: https://github.com/follow-redirects/follow-redirects#per-request-options
