### ISSUE TITLE
error on passing timeout value as string ('30000' instead of 30000)

### ISSUE THREAD

**Issue by sidgupta94** [follow-redirects/follow-redirects#162]
Log:

`ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "The \"msecs\" argument must be of type number. Received type string ('30000')",
    "code": "ERR_INVALID_ARG_TYPE",
    "stack": [
        "TypeError [ERR_INVALID_ARG_TYPE]: The \"msecs\" argument must be of type number. Received type string ('30000')",
        "    at validateNumber (internal/validators.js:125:11)",
        "    at getTimerDuration (internal/timers.js:381:3)",
        "    at TLSSocket.setStreamTimeout [as setTimeout] (internal/stream_base_commons.js:250:11)",
        "    at RedirectableRequest.destroyOnTimeout (/opt/nodejs/node_modules/follow-redirects/index.js:159:12)",
        "    at RedirectableRequest.emit (events.js:314:20)",
        "    at RedirectableRequest.EventEmitter.emit (domain.js:483:12)",
        "    at ClientRequest.eventHandlers.<computed> (/opt/nodejs/node_modules/follow-redirects/index.js:14:24)",
        "    at ClientRequest.emit (events.js:326:22)",
        "    at ClientRequest.EventEmitter.emit (domain.js:483:12)",
        "    at tickOnSocket (_http_client.js:709:7)"
    ]
}` 

In version 1.13.3, we used to pass the timeout value as string and it worked fine. After upgrading to version 1.14.0, on passing a string value as timeout ('30000') we are getting the above error.

**Comment by RubenVerborgh** [comment]
The API document says it it supposed to be a number: https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback
