### ISSUE TITLE
It is not working for a url

### ISSUE THREAD

**Issue by future-mine** [follow-redirects/follow-redirects#164]
https://e.s4p.jp/r?p=c3NfZXZfAQDLfb46GpiA_WIDlA5Pa3czSSLumKqVsLi_Upk5KqHh96WKHI7cSeoNMLnIiU9E7vJor2TNaArffGh10uNxUSf6qeKx40Kn05ia4zdSy2lNLSX1B5tKZJCPTub-fL-FfvK_XcUX2WLAUDx3Da4VvmN8jPUvo2tP0vWwBk8lgSjP600f1W2iLfavXNA1Sex42ikTK-hicsT6VWHgZ_QKWaqA9gXdS7iJ48LkPF4JkS2rOyiTTniPzT_c5uI2IX6-Xssd9C9ZO6uCiODqn6UxwSby8vNa-YTkYySb4ns3Akb5IMym0x1a6jjDdnK_WxsjFGCBSxzwgNNlwjc7477I2GTwo0UUpBYZO4HE4MOg5NXWNHsOY6--TrsPtzcDIFV0V6RB9WDep6EvQHSr5z3fB_TPOufuZyAxPdnXenSM5l0U_0YhvNrcheWrUJZ_Xk9WWmkmfe3_f7Ibd5sPeE5N8i5vBYQZtNTqgEpML7F_yr0Vb9ZGyVhHxwV2Sb57d23po0-XjwcXfUgrhA

I tried to use the module for this url.
But seems it is not working

**Comment by RubenVerborgh** [comment]
The URL just seems very slow:

```
time curl -i 'https://e.s4p.jp/r?p=c3NfZXZfAQDLfb46GpiA_WIDlA5Pa3czSSLumKqVsLi_Upk5KqHh96WKHI7cSeoNMLnIiU9E7vJor2TNaArffGh10uNxUSf6qeKx40Kn05ia4zdSy2lNLSX1B5tKZJCPTub-fL-FfvK_XcUX2WLAUDx3Da4VvmN8jPUvo2tP0vWwBk8lgSjP600f1W2iLfavXNA1Sex42ikTK-hicsT6VWHgZ_QKWaqA9gXdS7iJ48LkPF4JkS2rOyiTTniPzT_c5uI2IX6-Xssd9C9ZO6uCiODqn6UxwSby8vNa-YTkYySb4ns3Akb5IMym0x1a6jjDdnK_WxsjFGCBSxzwgNNlwjc7477I2GTwo0UUpBYZO4HE4MOg5NXWNHsOY6--TrsPtzcDIFV0V6RB9WDep6EvQHSr5z3fB_TPOufuZyAxPdnXenSM5l0U_0YhvNrcheWrUJZ_Xk9WWmkmfe3_f7Ibd5sPeE5N8i5vBYQZtNTqgEpML7F_yr0Vb9ZGyVhHxwV2Sb57d23po0-XjwcXfUgrhA' --http1.1 -L

real	0m20.211s
user	0m0.042s
sys	0m0.019s
```
