### ISSUE TITLE
unhandle error on timeout caus this._timeout is undefined

### ISSUE THREAD

**Issue by fatoldsun00** [follow-redirects/follow-redirects#169]
Hi,

we use axios module and we get an unhandle rejection on timeout caus clearTimeout of this._timeout is undefined,
you backup this in self, so it's not self._timeout instead of this._timeout ?

index.js, ln 174

```
var self = this;
...
// Prevent a timeout from triggering
  function clearTimer() {
    clearTimeout(this._timeout);
    if (callback) {
      self.removeListener("timeout", callback);
    }
    if (!this.socket) {
      self._currentRequest.removeListener("socket", startTimer);
    }
  }
```

**Comment by RubenVerborgh** [comment]
Do you have code to reproduce?

**Comment by fatoldsun00** [comment]
it's difficult cause it's on large app, we have add axios and now on request timeout we got an unhandle rejection.
