### ISSUE TITLE
Error Handling missing in case of Socket destroy by timeout 

### ISSUE THREAD

**Issue by vmatyusGitHub** [follow-redirects/follow-redirects#170]
I am using `follow-redirect` through `axios`.
I am testing now the timeout values and turned out a case, when a `socket.destroy` caused by a timeout does not trigger error handling. In this case the request unsuccessful, but I cannot catch this error. Could you please help me how to handle this specific failed response case.

Here is my current code:
```node
const service = CloudantV1.newInstance({timeout:20000});
try{
    var result= service.postChanges({
        db: "db",
        feed: CloudantV1.PostChangesConstants.Feed.LONGPOLL,
        since: "now",
        timeout: 25000,
    }).then(response => {
        console.log(response.result);
    }).catch(error => {
        console.log(error)
    }).finally(() => {
        console.log("Finally")
    });
    console.log(result)
}catch(e)
{
    console.log(e)
}
```

More detailedly, the socket destroy is triggered at [this line](https://github.com/follow-redirects/follow-redirects/blob/f26c6c627106cb002fa39cfc327f5a541223a1cf/index.js#L157)
In our request there is already a [`response` event](https://github.com/follow-redirects/follow-redirects/blob/f26c6c627106cb002fa39cfc327f5a541223a1cf/index.js#L192) was triggered.

The operation is good, I am missing just an error handling. 
An error message would good that a socket timeout has occurred.

**Comment by vmatyusGitHub** [comment]
Here I created a small change that depicts better that socket timeout handler that I am missing: https://github.com/follow-redirects/follow-redirects/compare/main...vmatyusGitHub:patch-1

**Comment by RubenVerborgh** [comment]
> when a `socket.destroy` caused by a timeout does not trigger error handling

It does trigger a `timeout` event though.

Our goal is to offer the same API as Node's native `http` and `https` modules.
Only if the behavior differs, it is considered to be a bug.

As far as I understand, Node socket timeouts trigger `timeout`, not `error`.

**Comment by vmatyusGitHub** [comment]
Then what is your suggestion, how shall I write my code to catch this triggered `timeout` event?
My problem is that I cannot handle the `timeout` triggered by `socket.destroy`. It just stops the application with exit code 0.

**Comment by RubenVerborgh** [comment]
Unfortunately, I can't give advice for this specific case, as there is no visible follow-redirects code in there.

**Comment by vmatyusGitHub** [comment]
If you use the package and the service you will find the `follow-redirects` is used there.

**Comment by vmatyusGitHub** [comment]
By the way I have added a `timeout` event listener like this: 

```node
const service = CloudantV1.newInstance({timeout:20000});
try{
    var myTimeoutHandler = function () {
        console.log("socket Timeout catched")
    }
    eventEmitter.on('timeout', myTimeoutHandler);
    var result= service.postChanges({
        db: "db",
        feed: CloudantV1.PostChangesConstants.Feed.LONGPOLL,
        since: "now",
        timeout: 25000,
    }).then(response => {
        console.log(response.result);
    }).catch(error => {
        console.log(error)
    }).finally(() => {
        console.log("Finally")
    });
    console.log(result)
}catch(e)
{
    console.log(e)
}
```

This code also could not handle the `socket.destroy` triggered timeout, still exit code 0 returned.
