### ISSUE TITLE
replace if (!this.socket) by  if (!self.socket)

### ISSUE THREAD

**Issue by fatoldsun00** [follow-redirects/follow-redirects#171]
Thanks for you previous [commit](https://github.com/follow-redirects/follow-redirects/commit/3f1b2f559083bd14b60265147e72deb510526098) 

there is still  an error on line 178 of index file, you check this.socket, i guess it's self.socket.

Thank for your great job.

**Comment by RubenVerborgh** [comment]
Hmmm that was sloppy from our side; and clearly the tests are not on point either. Will fix.
