### ISSUE TITLE
Relative redirect URLs target proxy server instead of upstream server

### ISSUE THREAD

**Issue by mbargiel** [follow-redirects/follow-redirects#179]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `follow-redirects@1.14.5` for the project I'm working on.

The problem I was running into is when using `axios` with a proxy and the upstream server returns a *relative* redirect URL, `follow-redirects` crafts an incorrect `redirectUrl` based on its cached `this._currentUrl`. It turns out that this URL is computed by using `url.format(this._options)`, which doesn't work correctly when a proxy server is configured because `this._options` is assumed to be an object containing valid `Url` parts, when it's in fact an object containing `ClientRequest` options with no guarantee that their semantics matches `Url` parts.

More specifically, the `axios` `http` adapter that uses `follow-redirects` modifies the original `options` by setting the `host`, `hostname` and `port` to the proxy's own host/port values, and `path` property to the full upstream server URL. (This, from what I know, is the correct way to configure a Node.js `http(s)` request to go through a proxy.) 

As a result, parsing the `ClientRequest` `options` as if it were a URL results in a weird URL like `http://<proxy-host-and-port>/https://<upstream-host-and-port>/<upstream-path>`, and when `follow-redirects` handles a *relative* redirect URL, it then uses this incorrect `currentUrl` as the base URL to use with `url.resolve`, and causes the redirected URL to be based the _proxy_ host rather than the _upstream_ host. A proxy like `mitmproxy` then detects the redirect as an attempt to connect to itself _through itself_ and immediately breaks the connection with a 502 error.

My solution is to try to resolve the request options' `path` property against this (semantically risky) "current URL". If `path` is an absolute URL, it will be used instead; if it's relative, then the original "current URL" will be unchanged. This makes `follow-redirects` "proxy-friendly" without explicitly adding proxy features. 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/follow-redirects/index.js b/node_modules/follow-redirects/index.js
index 7605d7d..eb0009c 100644
--- a/node_modules/follow-redirects/index.js
+++ b/node_modules/follow-redirects/index.js
@@ -277,7 +277,7 @@ RedirectableRequest.prototype._performRequest = function () {
   // Create the native request
   var request = this._currentRequest =
         nativeProtocol.request(this._options, this._onNativeResponse);
-  this._currentUrl = url.format(this._options);
+  this._currentUrl = url.resolve(url.format(this._options), this._options.path)
 
   // Set up event handlers
   request._redirectable = this;
```

Note that this was previously reported (https://github.com/follow-redirects/follow-redirects/issues/85) but the example snippet seemed to be incorrectly setup. In my case, I could fully reproduce this issue using [`mitmproxy`](https://mitmproxy.org/) and a local Node http server (very similar to that issue's http server, actually). This setup worked flawlessly with `curl`, and it works with absolute redirects.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mbargiel** [comment]
BTW, I am willing to draft up a proper PR with tests, if you are willing to consider taking this fix.

**Comment by RubenVerborgh** [comment]
> Firstly, thanks for your work on this project! 🙂

Well thank you for such a detailed problem description!



> BTW, I am willing to draft up a proper PR with tests, if you are willing to consider taking this fix.

You're amazing.

The first thing I'd need is one/a couple of example cases that fail. So those tests indeed, perhaps even with an actual proxy in the test case so we know it works properly.

I'm not 100% convinced yet by the fix; it might need to be a bit more elaborate, with explicit detection of the proxy case. But we can figure that out when the tests are in place.

Thanks in advance!

**Comment by mbargiel** [comment]
Hey, it's great to hear from you so quickly 😄 

As soon as I'm done shipping an update of our software with this patch in, I'll gladly follow-up with simple tests demonstrating the issue.

> perhaps even with an actual proxy in the test case so we know it works properly
Would `mitmproxy` work? Or did you mean that you'd rather have a nodejs-based implementation? I guess I could look at `node-http-proxy`, but I like that `mitmproxy` is pretty much good to go immediately, basically just a `brew install` command away and a CLI invocation.

**Comment by RubenVerborgh** [comment]
> Or did you mean that you'd rather have a nodejs-based implementation?

Yeah; best to keep it simple. The main issue is that the unit tests have to run on Node 4.x and up; I wonder if we can get away with simply https://stackoverflow.com/a/20354642/476820. If not, https://github.com/http-party/node-http-proxy might do (might need an older version for Node 4.x)).

**Comment by RubenVerborgh** [comment]
Or really just https://www.twilio.com/blog/node-js-proxy-server since we're using express already anyway in the tests.

**Comment by mbargiel** [comment]
Sorry for the spam, `axios`'s PR template bot is extremely aggressive and strict 😅

**Comment by mbargiel** [comment]
@RubenVerborgh Quick update - sorry for the delay, I still want to make that PR, I'm just looking for time to do it 😅

**Comment by mbargiel** [comment]
@RubenVerborgh Sorry again for the delay. I finally have some time to look at this. I was previously blocked while trying to get a PR up because of a test failure. I'll try moving that branch forward with the latest `main` branch revision. I'll keep you posted.

**Comment by RubenVerborgh** [comment]
Following up in #199.
