### ISSUE TITLE
Can't import in Symfony

### ISSUE THREAD

**Issue by KGB1st** [follow-redirects/follow-redirects#182]
I use encore and yarn, and getting an error 

> `symfony run yarn encore`

> Module build failed: Module not found:
> "./node_modules/follow-redirects/index.js" contains a reference to the file "http".
> This file can not be found, please check it for typos or update it if the file got moved.
> 
> "./node_modules/follow-redirects/index.js" contains a reference to the file "https".
> This file can not be found, please check it for typos or update it if the file got moved.
> 
> "./node_modules/follow-redirects/index.js" contains a reference to the file "stream".
> This file can not be found, please check it for typos or update it if the file got moved.
> 
> "./node_modules/follow-redirects/index.js" contains a reference to the file "assert".
> This file can not be found, please check it for typos or update it if the file got moved.

**Comment by RubenVerborgh** [comment]
Hi @KGB1st, this is a Symfony configuration problem, not a follow-redirects bug.

See https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed for more info.
