### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [follow-redirects/follow-redirects#183]
Hey there!

I belong to an open source security research community, and a member (@ranjit-git) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by RubenVerborgh** [comment]
Will add; for now please contact me personally https://ruben.verborgh.org/contact/

**Comment by JamieSlome** [comment]
@RubenVerborgh - our system will send you further details once the e-mail has been added, otherwise, you can view the details directly here:

https://huntr.dev/bounties/fc524e4b-ebb6-427d-ab67-a64181020406/

The report is private and only accessible to users with repository write permissions.

**Comment by RubenVerborgh** [comment]
Clear; thank you for your responsible disclosure. Fix to follow in the next couple of days.

**Comment by ranjit-git** [comment]
Thanks @RubenVerborgh
  happy to secure opensource project. 
Can you plz Mark the report as valid ?

**Comment by RubenVerborgh** [comment]
Fixed, thanks again for responsible disclosure.

**Comment by RubenVerborgh** [comment]
> Wouldn't it be a safer idea to _allow list_ headers to keep instead of dropping those two?

Yes, but the default behavior for unknown HTTP headers is to pass them on unmodified.

Note that it is the _user_ of the library who decides what headers are passed. They can decide to only pass specific headers. If they pass an unknown header, we are not responsible.
