### ISSUE TITLE
http(s) request method doesn't respect maxRedirects option

### ISSUE THREAD

**Issue by typoworx-de** [follow-redirects/follow-redirects#185]
I've noticed that follow-redirects 'http'(s) using get method works fine defining option 'maxRedirects: 3'. But trying the same with request-method doesn't work.

Using request instead of get can make sense, if one wants to quickly switch either using HTTP get or post. As follow-redirect aims to provide such functionality I would expect that the request method also can do that.

**Comment by RubenVerborgh** [comment]
This should not be the case. Could you please add code to reproduce?

**Comment by typoworx-de** [comment]
Hey. Don't know exactly what went wrong, did try from scratch and got it working.
