### ISSUE TITLE
Redirect from http to https fails when `agent` option is specified.

### ISSUE THREAD

**Issue by aiven715** [follow-redirects/follow-redirects#189]
When there's a redirect from the hostname with HTTP to HTTPS protocol, I'm getting the following error:
```
Redirected request failed: Protocol "https:" not supported. Expected "HTTP:"
```

Described behavior happens only when `agent` option is specified, otherwise, it works fine.

### Code to reproduce:
```js
var { http } = require("follow-redirects")

const request = http.request({
  method: 'get',
  hostname: 'github.com',
  agent: new http.Agent()
}, response => {
  response.on('data', chunk => {
    console.log(chunk);
  });
}).on('error', err => {
  console.log(err);
});
request.end()
```

Version used: 1.14.7

Related issue: #130

**Comment by RubenVerborgh** [comment]
> agents (default: undefined) – sets the agent option per protocol, since HTTP and HTTPS use different agents. Example value: { http: new http.Agent(), https: new https.Agent() }

—https://github.com/follow-redirects/follow-redirects/blob/2ede36d7c60d3acdcd324dcd99a9dbd52e4fb3a6/README.md#per-request-options
