### ISSUE TITLE
Please add statusCode

### ISSUE THREAD

**Issue by SergeBabich** [follow-redirects/follow-redirects#190]
https://github.com/follow-redirects/follow-redirects/blob/2ede36d7c60d3acdcd324dcd99a9dbd52e4fb3a6/index.js#L402

Just change this line, into: 
`var responseDetails = { headers: response.headers, statusCode: response.statusCode };`

Sometimes I need to redirect ONLY if the status is available for me.

Please, I need it ASAP

**Comment by RubenVerborgh** [comment]
See #191
