### ISSUE TITLE
v1.14.8 scheme change check broke my app

### ISSUE THREAD

**Issue by Cheyenne55** [follow-redirects/follow-redirects#192]
Hi,

I just ran npm audit fix and it broke my app, which shouldn't happen since the command is deemed to be retro-compatible.
It updated your package from 1.14.7 to 1.14.8 (as a dependency of Axios).

In my app architecture the requests can go from HTTP to HTTPS and vice-versa (but they stay on the same domain).
So now that you drop the auth headers when switching scheme it cannot work anymore.

If you keep the change I'd like to understand the reasons behind it so I can make the necessary fix.
Could you please elaborate on the reasons ?

(also as you can see this is a breaking change, so the version bump should have been the first digit, don't you think so ?)

**Comment by davidfurlong** [comment]
oof yes this got us too. brutal

**Comment by RubenVerborgh** [comment]
> made its way to prod

@davidfurlong Always interested to hear prod stories, feel free to tell more about how you use this library 🙂

**Comment by davidfurlong** [comment]
> @davidfurlong Always interested to hear prod stories, feel free to tell more about how you use this library 🙂

We use `axios` in a standard way which has `follow-redirects` as a dependency. Dependabot created a PR to fix a security vulnerability for `chore(deps): bump follow-redirects from 1.14.5 to 1.14.8 in /www` which passed our tests so was merged. Unfortunately this broke all our: login, signup, and authentication cookie redirects, but only in production

I think it's reasonable to suggest this was a breaking change for our project

**Comment by RubenVerborgh** [comment]
> I think it's reasonable to suggest this was a breaking change for our project

Definitely

> Unfortunately this broke all our: login, signup, and authentication cookie redirects

From HTTP to HTTPS or also the the way round?

(Separately: could you enlighten me why such redirects were in place? i.e., why it was not all HTTPS? That might help me understand similar issues in the future.)

**Comment by RubenVerborgh** [comment]
> so that our server side render requests use a local port (http) directly into to the api server.

Sounds like an HTTPS upgrade then indeed; I will fix that case.

**Comment by RubenVerborgh** [comment]
Patched in v1.14.9; thanks for the report.

**Comment by Cheyenne55** [comment]
Thanks

**Comment by xan187** [comment]
Yeh well it's cloud901memphis@gmail.com who's being robbed by girlfriend and mark Gianni owner of black swan. They are in my house porting me. I have all pass phrases. These GitHub's xan187 and 167 I cannot control

**Comment by xan187** [comment]
I only control this so no stones mainly this Mathis and pawal guy no one responds to me ever 9012873219 going to feeds on Monday
