### ISSUE TITLE
Integrity check failed for "follow-redirects"

### ISSUE THREAD

**Issue by cesumilo** [follow-redirects/follow-redirects#193]
Hi 👋 

I ran into an issue this afternoon when I executed "yarn" to install my dependencies. As part of them, I use "axios@^0.21.4" and it depends on follow-redirects. Since 1.14.8, I got the following issue:

```
https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.14.8.tgz: Integrity check failed for "follow-redirects" (computed integrity doesn't match our records, got "sha512-1x0S9UVJHsQprFcEC/qnNzBLcIxsjAV905f/UkQxbclCsoTWlacCNOpQa/anodLl2uaEKFhfWOvM2Qg77+15zA== sha1-AWmW+5oRoQBWY5ixxoOTN9e/qPw=")
```

Any idea why this happened?

Regards,

Guillaume

**Comment by RubenVerborgh** [comment]
I'm sorry, I could not tell you; is the "our records" perhaps an outdated cache file on your disk? Be sure the clear your lock files.

**Comment by AntoniosBarotsis** [comment]
I had the same issue on a freshly cloned repo that was working before/for someone else. I tried a few things like `audit fix` and clearing cache but in the end, switching the version to `1.14.7` in the lock file fixed it for me. Not sure what caused this but unless a package specifically needs `1.14.8` this should work.

**Comment by RubenVerborgh** [comment]
1.14.9 coming out soon.

**Comment by cesumilo** [comment]
> I had the same issue on a freshly cloned repo that was working before/for someone else. I tried a few things like `audit fix` and clearing cache but in the end, switching the version to `1.14.7` in the lock file fixed it for me. Not sure what caused this but unless a package specifically needs `1.14.8` this should work.

I did exactly the same fix, I had to update the lock file myself.
