### ISSUE TITLE
Break request in breforeRedirect event

### ISSUE THREAD

**Issue by 123bistami** [follow-redirects/follow-redirects#201]
Hello,

it is possible to break the redirecting in the beforeRedirect event and return the response, if yes how to do that, thank you

**Comment by 123bistami** [comment]
Can you give me a sample code pls. Thank you

**Comment by RubenVerborgh** [comment]
Hi @123bistami, the issue tracker is for bugs in the library. Thanks for your understanding.

**Comment by 123bistami** [comment]
> You would need to emit an `error` event on the argument `request`.

i need help with this redirecting package on github https://github.com/follow-redirects/follow-redirects.


const url = require('url');
const { http, https } = require('follow-redirects');

const options = url.parse(link);
options.maxRedirects = 10;
options.beforeRedirect = (options, response, request) => {
  if(response.url.includes('test')){
// abort request handle response in request response method
throw 'aborting';
}
};
http.request(options, (response) => {
console.log(response.responseUrl)
});


i will abort request in the beforeRedirect method and handle repsonse in the request response method. but if i throw an error i can't handle later in the response method. pls help, the package use nodejs http, https packages. i am not familiar with the http, https modules. thank you
