### ISSUE TITLE
A more specific way to test for relative redirect?

### ISSUE THREAD

**Issue by olaf-k** [follow-redirects/follow-redirects#206]
Hey Ruben!

I noticed you detect relative redirects by checking whether the returned Location matches "word chars followed by a colon", presumably to detect the presence of the protocol:
https://github.com/follow-redirects/follow-redirects/blob/76ea31f06823d8c2d9edfb3387995d78ca4b5d40/index.js#L403

Wouldn't that also catch redirects that contain colons in their path? (Which seems to be perfectly acceptable, e.g.: https://en.wikipedia.org/wiki/Template:Welcome) Maybe a more specific test like `/https?:/i` would do the trick?

**Comment by RubenVerborgh** [comment]
Hi Olaf,

We're fine because it matches "word chars followed by a colon **at the beginning of a string**", so it's a more generic version of the specific test you mention.

**Comment by olaf-k** [comment]
I realize my initial post was a tad confusing.

What I meant to ask is: if you only test for absolute paths with a colon (at the start of the string), wouldn't you get false-positive for some relative paths containing this character?
E.g.: a 301 with `Location` containing only `Template:Welcome` would be identified as an absolute path

Or maybe you assume that relative paths should always start with a forward slash (in which case `\w` won't indeed match)?

**Comment by olaf-k** [comment]
Oh well, I guess I should have read the specs first: https://www.rfc-editor.org/rfc/rfc3986#section-4.2
Relative paths must begin with at least 1 forward slash indeed.
Sorry for the noise!

**Comment by RubenVerborgh** [comment]
No worries, good to have extra pairs of eyes on this 👍

**Comment by 0956397203** [comment]
hi

**Comment by 0956397203** [comment]
Ih
