### ISSUE TITLE
Failing for dead or unreachable sites (403, 404)

### ISSUE THREAD

**Issue by drveresh** [follow-redirects/follow-redirects#208]
Hi,

The redirect isn't working for some URLs that aren't 200 or especially 404 or 403, or similar potential dead or inactive host sites.  It should return the last domain/site name irrespective of its live status.

I am getting the below error or response for such URLs: http://bitly.ws/siHN, http://bitly.ws/siYS, https://rb.gy/k7dzbn

Ref - https://wheregoes.com/trace/20223747272/ 
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:130:17).
```
    
For instance, the link http://bitly.ws/siHN is going to the target site at https://live326.wixsite.com/my-site and it is dead or not reachable state, with a status 404.  But, [follow-redirects](https://github.com/follow-redirects/follow-redirects) return nothing in response, not even any clue or hints in the error object.

This is a **very critical use case**, especially in security events, so I request you to fix this at **HIGH** priority!

**Comment by drveresh** [comment]
I just tried [follow-redirect-url](https://www.npmjs.com/package/follow-redirect-url), and it solved this problem seamlessly, and able reach the last sites whether it is dead/unreachable.

**Comment by RubenVerborgh** [comment]
> I request you to fix this at HIGH priority!

https://github.com/sponsors/RubenVerborgh
