### ISSUE TITLE
TypeError crashing application when using relative URL from axios

### ISSUE THREAD

**Issue by qooban** [follow-redirects/follow-redirects#211]
I got the following error coming from `follow-redirects`:
```
/.../node_modules/follow-redirects/index.js:598
  const dot = subdomain.length - domain.length - 1;
                                        ^
TypeError: Cannot read property 'length' of null
    at isSubdomain (/.../node_modules/follow-redirects/index.js:598:41)
    at RedirectableRequest._processResponse ((/.../node_modules/follow-redirects/index.js:432:7)
    at ClientRequest.RedirectableRequest._onNativeResponse ((/.../node_modules/follow-redirects/index.js:57:10)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
```
and it happens when HTTP client (`axios`) is trying to do GET request on relative URL: `/console/external/content?url=https%3A%2F%2F...%2Faws.png`.

From my quick investigation it seems like `currentHost` passed to `isSubdomain` function is `null`, but inside that function it is assumed that this parameter is a string.

Attachments:
This are dumps of some data in `RedirectableRequest.prototype._processResponse` function:
* `this._options` - [options.txt](https://github.com/follow-redirects/follow-redirects/files/9414184/options.txt)
* `response` - [response.txt](https://github.com/follow-redirects/follow-redirects/files/9414185/response.txt)

Environment:
* `node` - v14.18.1
* `axios` - v0.26.1
* `follow-redirects` - v1.15.1
* nginx HTTPS webserver running on localhost

Not sure if it is on `follow-redirects` or on `axios` side, but that specific error is not handled and it crashes the app. Other errors like invalid URL when using absolute URLs are handled flawlessly.

Let me know if any additional data needed or if I should pass this issue to `axios` guys.

**Comment by RubenVerborgh** [comment]
> it happens when HTTP client (`axios`) is trying to do GET request on relative URL: `/console/external/content?url=https%3A%2F%2Frepository.cloudifysource.org%2Fcloudify%2Fblueprints%2F5.1%2Fimages%2Faws.png`.
> 
> From my quick investigation it seems like `currentHost` passed to `isSubdomain` function is `null`, but inside that function it is assumed that this parameter is a string.

I'm trying to figure out how `currentHost` can be `null`. Even though the redirect is relative, there should have been an original host.
Do you have the chain of redirection URLs?

**Comment by qooban** [comment]
@RubenVerborgh 

Thanks for taking care of this. I did some tests using `curl` and `wget` and the chain seems to be just:
`http://localhost/...` -> 308 Permanent Redirect -> `https://localhost/...`. No more redirects.

I believe similar redirect happened when we do call from `axios`.

I can add some more checks/console.logs in follow-redirect and check. Please just guide me a bit in that. 
I can keep my test VM up and running for one week.

**Comment by qooban** [comment]
After playing with `axios-debug-log` I managed to get the following logs:

```
[2022-09-09T12:39:39.743Z][DBMigration] INFO: Fetching icon from URL: /console/external/content?url=https%3A%2F%2F<...anonymized...>%2Faws.png...
  axios {
  axios   transitional: {
  axios     silentJSONParsing: true,
  axios     forcedJSONParsing: true,
  axios     clarifyTimeoutError: false
  axios   },
  axios   adapter: [Function: httpAdapter],
  axios   transformRequest: [ [Function: transformRequest] ],
  axios   transformResponse: [ [Function: transformResponse] ],
  axios   timeout: 0,
  axios   xsrfCookieName: 'XSRF-TOKEN',
  axios   xsrfHeaderName: 'X-XSRF-TOKEN',
  axios   maxContentLength: -1,
  axios   maxBodyLength: -1,
  axios   validateStatus: [Function: validateStatus],
  axios   headers: {
  axios     common: { Accept: 'application/json, text/plain, */*' },
  axios     delete: {},
  axios     get: {},
  axios     head: {},
  axios     post: { 'Content-Type': 'application/x-www-form-urlencoded' },
  axios     put: { 'Content-Type': 'application/x-www-form-urlencoded' },
  axios     patch: { 'Content-Type': 'application/x-www-form-urlencoded' }
  axios   },
  axios   responseType: 'arraybuffer',
  axios   method: 'get',
  axios   url: '/console/external/content?url=https%3A%2F%2<...anonymized...>%2Faws.png'
  axios } +21ms
  axios Request with undefined +0ms
/opt/cloudify-stage/backend/node_modules/follow-redirects/index.js:592
  const dot = subdomain.length - domain.length - 1;
                                        ^
TypeError: Cannot read property 'length' of null
    at isSubdomain (/opt/cloudify-stage/backend/node_modules/follow-redirects/index.js:592:41)
    at RedirectableRequest._processResponse (/opt/cloudify-stage/backend/node_modules/follow-redirects/index.js:427:7)
    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/cloudify-stage/backend/node_modules/follow-redirects/index.js:57:10)
```

so it doesn't get to the point when axios response is logged.

I'm not sure if that's helpful...

**Comment by RubenVerborgh** [comment]
@qooban Mmm, could you please log the `curl -I -L your_url`?

**Comment by qooban** [comment]
@RubenVerborgh Sure, here it is:

```
$ curl -I -L http://localhost/console/external/content?url=https%3A%2F%2F...%2Faws.png

HTTP/1.1 308 Permanent Redirect
Server: nginx
Date: Fri, 09 Sep 2022 13:11:30 GMT
Content-Type: text/html
Content-Length: 164
Connection: keep-alive
Location: https://localhost/console/external/content?url=https%3A%2F%2F...%2Faws.png
Referrer-Policy: same-origin
X-Content-Type-Options: nosniff

curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by RubenVerborgh** [comment]
And with a `-k` added to it?

**Comment by qooban** [comment]
@RubenVerborgh Here it is:

```
$ curl -I -L -k http://localhost/console/external/content?url=https%3A%2F%2F...%2Faws.png

HTTP/1.1 308 Permanent Redirect
Server: nginx
Date: Mon, 12 Sep 2022 06:47:38 GMT
Content-Type: text/html
Content-Length: 164
Connection: keep-alive
Location: https://localhost/console/external/content?url=https%3A%2F%2F...%2Faws.png
Referrer-Policy: same-origin
X-Content-Type-Options: nosniff

HTTP/1.1 502 Bad Gateway
Server: nginx
Date: Mon, 12 Sep 2022 06:47:38 GMT
Content-Type: text/html
Content-Length: 150
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

**Comment by RubenVerborgh** [comment]
> it happens when HTTP client (`axios`) is trying to do GET request on relative URL

I'm not seeing the relative URL above though. I'm starting to think that Axios is just being used wrongly here. What's your code snippet that uses Axios?

**Comment by qooban** [comment]
This is the exact line calling Axios: https://github.com/cloudify-cosmo/cloudify-stage/blob/3e48291471b9e9be34d1f12d8ce2703bf0a43434/backend/migrations/20220527182401-6_4-RemoveBlueprintAdditionsTable.ts#L34

`imageUrl` in our case is `/console/external/content?url=https%3A%2F%2F...%2Faws.png`

**Comment by qooban** [comment]
Yeah, you're right. When using axios in browser relative URL should work, but in node.js environment (this is my case) it has no way to know how to transform it, so `baseURL` should be specified in axios config. When I set it (`{ baseURL: 'https://localhost' }`), my migration script is not crashing anymore.

Thanks for your patience and willingness to find the reason for the problem!

**Comment by RubenVerborgh** [comment]
Thanks @qooban. v1.15.2 will now handle this gracefully by defaulting to localhost (6e2b86da90cde81f15a5ba1732a41fd1291f14d3), as Node does. However, I still recommend you use the full URL, as it seems to be a pure coincidence that it is indeed `localhost` in your case 🙂
