### ISSUE TITLE
Consider printing a warning when dropping confidential headers before redirecting from HTTP to HTTPS

### ISSUE THREAD

**Issue by eyalch** [follow-redirects/follow-redirects#233]
The logic of dropping confidential headers (e.g., `Authorization` or `Cookie`) when redirecting to a less secure protocol (from HTTP to HTTPS) makes sense, but very easy to overlook. 

I spend over an hour trying to debug a simple request made via [Axios](https://github.com/axios/axios). Imagine that `http://example.com` redirects to `https://example.com`:

```js
axios.get("http://example.com", {
  headers: {
    Authorization: "Bearer abc123",
  }
})
```

Here's the logic that drops confidential headers when redirecting from HTTP to HTTPS:
https://github.com/follow-redirects/follow-redirects/blob/bcbb096b32686ecad6cd34235358ed6f2217d4f0/index.js#L439-L446

I suggest printing a warning before/after dropping the headers, for example:

```diff
   // Drop confidential headers when redirecting to a less secure protocol
   // or to a different domain that is not a superdomain
   if (redirectUrlParts.protocol !== currentUrlParts.protocol &&
      redirectUrlParts.protocol !== "https:" ||
      redirectUrlParts.host !== currentHost &&
      !isSubdomain(redirectUrlParts.host, currentHost)) {
     removeMatchingHeaders(/^(?:authorization|cookie)$/i, this._options.headers);
+    console.warn(`removed confidential headers before redirecting to ${redirectUrl}`);
   }
```

I'm not sure if a call to `debug` will be good enough, since in my case I wouldn't have seen it anyway.

**Comment by RubenVerborgh** [comment]
Good point, but I don't think `fetch` warns in such cases. My go-to would indeed to use `debug`, but that wouldn't solve your problem. Although I think it's still the best thing, at least it can help people debug following the README. Would that be a good resolution?

**Comment by eyalch** [comment]
Not sure I understand the suggested solution. Are you suggesting to set the `DEBUG` environment variable? Even though I was technically trying to debug an issue, I didn't think of setting the `DEBUG` environment variable. I doubt that most people will think of setting it. Would you say that it's common enough to expect people to set it?

Regarding improving the README, I doubt that it would've helped me, since it took me quite some time to even figure out that the issue is related to `follow-redirects`.

**Comment by RubenVerborgh** [comment]
Probably no solution is really common enough for people to figure it out without checking the README. It's a hard balance between being unobtrusive and not surprising. Axios is the most common user of follow-redirects, perhaps they might want to add it to their README too (but unsure if they use `DEBUG` elsewhere).

I'll close this one for now, but happy to accept suggestions.

**Comment by eyalch** [comment]
Somehow, I slipped on the same banana once more, and again I spend significant time trying to debug this exact issue.

As mentioned above, from a security perspective, this behavior of removing confidential headers when switching protocols makes sense, but it's super unintuitive!

Please reconsider _unconditionally_ logging the removal of confidential headers. This would be super helpful!

**Comment by RubenVerborgh** [comment]
Unconditionally would lead to undesired behavior upstream; our consumers do not expect for follow-redirects to start writing to the console without being asked to.

**Comment by Bokoness** [comment]
I ran into a similar problem debugging an `Axios` request and spent over an hour figuring out what was going on. The idea of ditching confidential headers when redirecting from HTTP to HTTPS in follow-redirects makes sense, but it's a sneaky detail that's easy to miss during troubleshooting.
