### ISSUE TITLE
Does not follow Google RSS news redirects

### ISSUE THREAD

**Issue by audas** [follow-redirects/follow-redirects#234]
For example this will return the same link - even though it redirects.

https://news.google.com/rss/articles/CBMicGh0dHBzOi8vd3d3LmFiYy5uZXQuYXUvbmV3cy8yMDIzLTEwLTE3L2JhcmJlY3VlLWJydXNoLXdhcm5pbmctYWZ0ZXItbmVhci1mYXRhbC1iYWNvbi
1hbmQtZWdnLXJvbGwtbWVhbC8xMDI5Njg3NTjSAQA?oc=5&hl=en-AU&gl=AU&ceid=AU:en

The original link google provides for the article, when followed is thus:

_______________ORIGINAL__________url
https://news.google.com/rss/articles/CBMiygFodHRwczovL3d3dy5hZGVsYWlkZW5vdy5jb20uYXUvdHJ1ZWNyaW1lYXVzdHJhbGlhL3BvbGljZS1jb3VydHMtc2EvY291cnQtdG9sZC1yYWluYS
1jcnVpc2UtYWxsZWdlZGx5LXRvbGQtZmVtYWxlLXBvbGljZS1vZmZpY2VyLWktd2lsbC1zbWFzaC15b3Utb25lb25vbmUtYnRjaC9uZXdzLXN0b3J5L2ViMzNlOGVhMjU0ZTFjYWIxNDMwMDJhZDJmZDcwM
jQ00gEA?oc=5

_RESPONSE____________url
https://news.google.com/rss/articles/CBMiygFodHRwczovL3d3dy5hZGVsYWlkZW5vdy5jb20uYXUvdHJ1ZWNyaW1lYXVzdHJhbGlhL3BvbGljZS1jb3VydHMtc2EvY291cnQtdG9sZC1yYWluYS
1jcnVpc2UtYWxsZWdlZGx5LXRvbGQtZmVtYWxlLXBvbGljZS1vZmZpY2VyLWktd2lsbC1zbWFzaC15b3Utb25lb25vbmUtYnRjaC9uZXdzLXN0b3J5L2ViMzNlOGVhMjU0ZTFjYWIxNDMwMDJhZDJmZDcwM
jQ00gEA?oc=5&hl=en-AU&gl=AU&ceid=AU:en

The above response URL when followed, as mentioned returns the same url, even though it redirects.

**Comment by RubenVerborgh** [comment]
> even though it redirects.

It doesn't though.

Here's the request with the built-in `https` module:

```javascript
const https = require('https');

const url = 'https://news.google.com/rss/articles/CBMicGh0dHBzOi8vd3d3LmFiYy5uZXQuYXUvbmV3cy8yMDIzLTEwLTE3L2JhcmJlY3VlLWJydXNoLXdhcm5pbmctYWZ0ZXItbmVhci1mYXRhbC1iYWNvbi1hbmQtZWdnLXJvbGwtbWVhbC8xMDI5Njg3NTjSAQA?oc=5&hl=en-AU&gl=AU&ceid=AU:en';

https.get(url, response => {
  console.log(response.statusCode);
});

// 200
```

That might come as a surprise, given that:

```shell
% curl -i -s 'https://news.google.com/rss/articles/CBMicGh0dHBzOi8vd3d3LmFiYy5uZXQuYXUvbmV3cy8yMDIzLTEwLTE3L2JhcmJlY3VlLWJydXNoLXdhcm5pbmctYWZ0ZXItbmVhci1mYXRhbC1iYWNvbi1hbmQtZWdnLXJvbGwtbWVhbC8xMDI5Njg3NTjSAQA?oc=5&hl=en-AU&gl=AU&ceid=AU:en' | head -n 1
# HTTP/2 302
```

However, the difference is that curl sends out a `User-Agent` header by default.

This works as expected:

```javascript
const { https } = require('follow-redirects');

const url = 'https://news.google.com/rss/articles/CBMicGh0dHBzOi8vd3d3LmFiYy5uZXQuYXUvbmV3cy8yMDIzLTEwLTE3L2JhcmJlY3VlLWJydXNoLXdhcm5pbmctYWZ0ZXItbmVhci1mYXRhbC1iYWNvbi1hbmQtZWdnLXJvbGwtbWVhbC8xMDI5Njg3NTjSAQA?oc=5&hl=en-AU&gl=AU&ceid=AU:en';

https.get(url, { headers: { 'user-agent': 'whatever' } }, response => {
  console.log(response.responseUrl);
});
```

So the bug is actually that Google News doesn't redirect without a `User-Agent` header.
