### ISSUE TITLE
Call Error.captureStackTrace on firefox crash the app

### ISSUE THREAD

**Issue by Moonnz** [follow-redirects/follow-redirects#237]
Hello :)

Recently we see a problem appearing on our app only on Firefox.
After few hours of research, I've discovered that this is caused by the new version 1.15.4 required by Axios.

The modification on this version lead to a call to Error.captureStackTrace on Firefox (Where it doesn't exist, because it's not V8)

The solution for me was to force the dependency to the version 1.15.3.

**Comment by RubenVerborgh** [comment]
Hi @Moonnz,

> Recently we see a problem appearing on our app only on Firefox.

Yeah, `follow-redirects` must not and cannot be used in browsers. It's a module for Node that emulates browser functionality. If it appears in your browser version, something's wrong with your compilation pipeline: it should be substituted with your browser's native version.
