### ISSUE TITLE
EMERGENT!!! huntr security reporting page is not working for follow-redirects

### ISSUE THREAD

**Issue by 4xpl0r3r** [follow-redirects/follow-redirects#248]
I have located a vulnerability in `follow-redirects`, want to report it through `huntr` since your security policy says every security advisory has to be reported through it. Now I'm unable to submit my report, can you fix this issue ASAP?

![image](https://github.com/follow-redirects/follow-redirects/assets/20693041/8bd10dd8-bafa-4d20-aa04-8f821ee63ac3)

**Comment by RubenVerborgh** [comment]
You can email me via https://ruben.verborgh.org/contact/ (3rd option)

**Comment by RubenVerborgh** [comment]
Thanks a lot, disclosed as https://github.com/follow-redirects/follow-redirects/security/advisories/GHSA-cxjh-pqwp-8mfp and fixed in v1.15.6.
