### ISSUE TITLE
### Describe the bug

### ISSUE THREAD

**Issue by Pjrich1313** [follow-redirects/follow-redirects#251]
### Describe the bug

Version 1.6.4 and later will sometimes cause the basic authentication to fail, seemingly randomly. When passing the credentials of an http request, sometimes the server will return 401 error. So far it seems to happen to only certain endpoints of the same server (Flask), even if the requests are otherwise identical. Reversing to version 1.6.3 fixes the issue. After some digging, it seems to be caused by the follow-redirects module version 1.15.4.  Downgrading the module to version 1.15.3 will also fix the problem. 
Current workaround without downgrading is to pass the Authorization header instead of the auth property in configuration when making a request.

### Axios Version

1.6.4

_Originally posted by @wanghe001 in https://github.com/axios/axios/issues/6179_

**Comment by RubenVerborgh** [comment]
See #243
