### ISSUE TITLE
Replace deprecated `url.parse`

### ISSUE THREAD

**Issue by jirimoravcik** [follow-redirects/follow-redirects#257]
The deprecated `url.parse` is still used in https://github.com/follow-redirects/follow-redirects/blob/35a517c5861d79dc8bff7db8626013d20b711b06/index.js#L561

It would be nice to replace it.

**Comment by RubenVerborgh** [comment]
https://github.com/follow-redirects/follow-redirects/commit/05629af696588b90d64e738bc2e809a97a5f92fc

**Comment by jirimoravcik** [comment]
Hey, thanks for the quick response, but I still see the usage in https://github.com/follow-redirects/follow-redirects/blob/main/index.js#L561

**Comment by RubenVerborgh** [comment]
Indeed, in an `else` condition of a check that the running version of Node supports `url.parse` alternatives.
On sufficiently recent Node versions, `url.parse` is never used. But older versions leave us no choice, and our compatibility obligation starts at Node 4: https://github.com/follow-redirects/follow-redirects/actions/runs/8284368057

**Comment by jirimoravcik** [comment]
> Indeed, in an `else` condition of a check that the running version of Node supports `url.parse` alternatives. On sufficiently recent Node versions, `url.parse` is never used. But older versions leave us no choice, and our compatibility obligation starts at Node 4: https://github.com/follow-redirects/follow-redirects/actions/runs/8284368057

Ok, thanks for the explanation 👏
