### ISSUE TITLE
Return statement outside of function

### ISSUE THREAD

**Issue by jjac111** [follow-redirects/follow-redirects#266]
Hello there! 
Since the last update to `follow-redirects` about an hour ago there seems to be [a JS syntax error here](https://github.com/follow-redirects/follow-redirects/blob/fda0fafa0c8d197cbcd232d98c68445ed323c337/index.js#L14)

This is currently breaking Next.JS builds because there is a `return` statement outside of a function.
@RubenVerborgh maybe you are working on this right now?

**Comment by RubenVerborgh** [comment]
Node.js happily takes it though; but I think that's because it's internally wrapping each file in a function. Let me look.

**Comment by jjac111** [comment]
Thank you so much!
