### ISSUE TITLE
Latest patch broke redirects for me. 1.15.8

### ISSUE THREAD

**Issue by sirisian** [follow-redirects/follow-redirects#267]
I was on 1.15.6 previously and was testing something completely separate in my project when I noticed redirects stopped working and it seems to have been caused when the package updated to 1.15.8. I rolled back to the package to 1.15.6 and it worked again.

I didn't investigate much. My code is fairly simple, so I didn't notice anything obvious. (I forgot to grab the logs, but from what I remember I think it was calling the callback with the 302 response).
```js
import { http, https } from 'follow-redirects';
//....
const httpOrHttps = url.toLowerCase().startsWith('https:') ? https : http;
this.request = httpOrHttps.get(url, {}, response => {
//...
});
```

**Comment by RubenVerborgh** [comment]
I'm sorry to hear that, but the above test case absolutely works.
I'm suspecting your compilation pipeline—are you writing for Node.js or the browser?

**Comment by RubenVerborgh** [comment]
Oh no… it must be ESM defaulting to the `browser` version or so.

**Comment by RubenVerborgh** [comment]
Yes, it's your compilation pipeline playing tricks. `follow-redirects` has no specific ESM support at the moment, so the code to important the untranspiled version would be:

```
import { default as followRedirects } from 'follow-redirects';
const { http, https } = followRedirects;
```

Feel free to post your configuration here; might look into an ESM version.

**Comment by sirisian** [comment]
This is being ran in nw.js in a node.js environment after bundling with webpack. So that is probably what's causing problems.

Looking at the commit logs I see comments about graceful browser degradation. https://github.com/follow-redirects/follow-redirects/commit/97d1f9a49a001eb50aa7bf00515182622b2b25a1 Perhaps that isn't playing well with nw.js.

I don't use the browser field in my package.json. (This is a fairly basic nw.js project).

```json
{
	"name": "...",
	"main": "index.html",
	"window": {
		...
	},
	"webkit": {
		"plugin": true
	},
	"permissions": [
		...
	],
	"scripts": {
		"build": "webpack --mode=development --config webpack.config.js"
	},
	"dependencies": {
		...,
		"follow-redirects": "1.15.6",
		...
	},
	"devDependencies": {
		...
	}
}

```

My webpack.config.js is:

```js
const path = require('path');
const TerserPlugin = require("terser-webpack-plugin");
const webpack = require('webpack');
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
	devtool: 'source-map',
	context: path.resolve(__dirname, ''),
	entry: {
		container: './src/container.js'
	},
	target: 'nwjs',
	node: {
		__dirname: true,
		__filename: true
	},
	output: {
		publicPath: '',
		filename: '[name]-bundle.js',
		path: path.resolve(__dirname, 'dist'),
		clean: true
	},
	module: {
		rules: [
			{
				test: /\.css$/i,
				oneOf: [
					{ assert: { type: "css" }, loader: "css-loader", options: { exportType: 'css-style-sheet' } },
					{ use: ["style-loader", "css-loader"] }
				]
			},
			{
				test: /\.(png|jpe?g|gif|svg)$/,
				type: 'asset/resource',
				generator: {
					filename: './images/[name][ext]'
				}
			},
			{
				test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
				type: 'asset/resource',
				generator: {
					filename: './fonts/[name][ext]'
				}
			}
		],
	},
	plugins: [
		new CopyPlugin({
			patterns: [
			],
		})
	],
	resolve: {
		modules: [
			path.resolve(__dirname, 'src'),
			'node_modules',
		],
		fallback: {
			"querystring": require.resolve("querystring-es3")
		}
	},
	optimization: {
		usedExports: true,
		minimize: false,
		minimizer: [
			new TerserPlugin({
				extractComments: false
			}),
		],
	}
};
```

This has been basically unchanged since 2021 in my build system, so it's been a while since I've touched it.

**Comment by RubenVerborgh** [comment]
Thanks for sharing—interesting. Didn't know about NW.js.
So that's basically an environment that's… both Node and browser I presume?

> I don't use the browser field in my package.json.

Ah but we do in 1.15.8: https://github.com/follow-redirects/follow-redirects/blob/v1.15.8/package.json#L7
But it might not be that, it could equally be: https://github.com/follow-redirects/follow-redirects/blob/v1.15.8/nope.js#L14
Are you seeing this warning in the console?

Curiosity question: how come you're not using `fetch`, given that it's probably available in NW.js?

**Comment by RubenVerborgh** [comment]
Related: https://stackoverflow.com/questions/31968355/detect-if-web-app-is-running-in-nwjs

**Comment by sirisian** [comment]
> Curiosity question: how come you're not using fetch, given that it's probably available in NW.js?

Long story, but the project used pepper plugins and old versions of Chrome/nw.js. I only recently removed all of that and you're completely right. I can just use fetch and ```redirect: 'follow'``` like I do in other projects. Just made that quick change.

**Comment by RubenVerborgh** [comment]
Thanks for your help! I'm reverting the change in 31a1abf2d659ac1c8fcbe7e614a8c8914d80e1e3.
