### ISSUE TITLE
isBrowser never returned true

### ISSUE THREAD

**Issue by trew** [follow-redirects/follow-redirects#268]
This commit removed isBrowser() and the early out in index.js: https://github.com/follow-redirects/follow-redirects/commit/a8d1ceed257d46758f913ff555b4f7e1cd758627

isBrowser was implemented as follows:
`return browser && !!console.warn("Exclude follow-redirects from browser builds.");`

This always returns false, since `!!console.warn(...)` always returns false, and that means the early out in index.js that was removed also never triggered.

That also means the wrap function is now actually referencing nope.wrap in browsers. I don't know much about this package, but it upgraded as a transitive dependency in my insomnia plugin, which got broken as a result. 1.15.7 works, 1.15.8 doesn't.

**Comment by RubenVerborgh** [comment]
> That also means the wrap function is now actually referencing nope.wrap in browsers.

That's the way it's supposed to work; follow-redirects must not be used in browsers.
Not sure why it's broken though; `wrap` just returns the native `http` and `https`, since it can't take over redirects from the browser anyway. What kind of breakage are you expecting?

**Comment by trew** [comment]
I figured that it was the intended behavior. I'm not entirely sure why it breaks. A request is being made using axios and it no longer provides the correct payload. The axios instance is configured to use the "http" adapter, since I don't want this request to actually use a browser context (I need to keep track of cookies myself).

**Comment by trew** [comment]
> follow-redirects must not be used in browsers

_must_ not, or _should_ not? Does it break completely if the follow-redirects is loaded or is it just that any interaction with it is meaningless?

**Comment by RubenVerborgh** [comment]
Not the latest.

**Comment by trew** [comment]
Electron is tricky though, since it's both node and browser, and you can't determine based on the environment only whether it's invalid use or not. If I use an "xhr" or "fetch" adapter with axios then follow-directs isn't used, but I need to use the "http" adapter, which uses node.

**Comment by RubenVerborgh** [comment]
Yeah I'm probably going to roll back the whole thing.

**Comment by Kauhsa** [comment]
Perhaps a bit offtopic, but wanted to comment here that the whole check/warning is perhaps a bit tricky in some testing setups (I test too far, but I suspect Node + JSDom being set up in global variables triggers the condition).

Ended up here since `axios` uses this package and got quite a lot of new console warnings when running tests after updating dependencies 😅

**Comment by mschilde** [comment]
> Not the latest.

Ah sorry, I probably missed something. I had 1.15.7 installed locally somehow, which caused issues in jest.

**Comment by kouts** [comment]
I'm using Vitest and started to get an `Exclude follow-redirects from browser builds.` error when running the tests.
I believe it's due to this issue.
Adding `resolutions` to `package.json` to use `v1.15.6` solved it for me.
```
"resolutions": {
  "follow-redirects": "1.15.6"
}
```

**Comment by RubenVerborgh** [comment]
Thanks all, I'm reverting to a gentle warning.
