### ISSUE TITLE
Library hangs infinitely on http://tinyurl.com/3pe4y42

### ISSUE THREAD

**Issue by clemensv** [follow-redirects/follow-redirects#273]
I'm having a request hang infinitely on a double redirect that returns a 307 followed by a 301 and another 301 and an 503 thereafter;

http://tinyurl.com/3pe4y42 

Thread hangs at https://github.com/follow-redirects/follow-redirects/blob/main/index.js#L659

**Comment by RubenVerborgh** [comment]
Server error:

```bash
curl -i -L 'http://tinyurl.com/3pe4y42'
```

hangs too.

**Comment by clemensv** [comment]
Unacceptable. Chrome/Edge do not hang but eventually resolve to a page. 

You've got a supposedly universal HTTP client library that can be DoS'ed into hanging infinitely by a link?

**Comment by schlazor** [comment]
FWIW it appears that you can get that server to respond if you include the following headers:

```
'User-Agent: Mozilla/5.0'
'Accept-Encoding: gzip, deflate'
'Connection: keep-alive'
```

**Comment by RubenVerborgh** [comment]
> Unacceptable.

That would be status code `406`. curl clearly shows it's a `301` though.

> get that server to respond if you include the following headers

Thanks @schlazor. This addresses the problem where it occurs.
